// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aigtd/HomeScreen.tsx": () => import("../components/mockups/aigtd/HomeScreen.tsx"),
  "./components/mockups/aigtd/InboxScreen.tsx": () => import("../components/mockups/aigtd/InboxScreen.tsx"),
  "./components/mockups/aigtd/NotesScreen.tsx": () => import("../components/mockups/aigtd/NotesScreen.tsx")
};
